version: "1"
services:
  backend:
    path: "./backend"
    build:
      builder: "DOCKERFILE"
      dockerfilePath: "./backend/Dockerfile"
    deploy:
      restartPolicyType: "ON_FAILURE"
      restartPolicyMaxRetries: 10
    ports:
      - 8081:8081

  frontend:
    path: "./frontend"
    build:
      builder: "DOCKERFILE"
      dockerfilePath: "./frontend/Dockerfile"
    deploy:
      restartPolicyType: "ON_FAILURE"
      restartPolicyMaxRetries: 10
    ports:
      - 8080:8080