version: "1"

services:
  backend:
    build:
      builder: "DOCKERFILE"
      dockerfilePath: "./backend/Dockerfile"
    deploy:
      restartPolicyType: "ON_FAILURE"
      restartPolicyMaxRetries: 10

  frontend:
    build:
      builder: "DOCKERFILE"
      dockerfilePath: "./frontend/Dockerfile"
    deploy:
      restartPolicyType: "ON_FAILURE"
      restartPolicyMaxRetries: 10