name: CI/CD
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Railway CLI
      run: |
        curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
    - name: Deploy backend
      if: contains(github.event.head_commit.modified, 'backend/')
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service backend
    - name: Deploy frontend
      if: contains(github.event.head_commit.modified, 'frontend/')
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service frontend
    - name: Verify deployment
      run: |
        railway status