name: CI/CD
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Railway CLI
      run: |
        curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
    - name: Deploy backend
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        BACKEND_SERVICE_ID: ${{ secrets.BACKEND_SERVICE_ID }}
      run: |
        railway up --service $BACKEND_SERVICE_ID
    - name: Deploy frontend
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        FRONTEND_SERVICE_ID: ${{ secrets.FRONTEND_SERVICE_ID }}
      run: |
        railway up --service $FRONTEND_SERVICE_ID