name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Railway CLI
      run: |
        curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway run --service backend
        railway run --service frontend
    - name: Verify deployment
      run: |
        railway status